-- ดู event ล่าสุด
SELECT * FROM TRACKING_EVENTS ORDER BY CREATED_AT DESC;

-- เปรียบเทียบ A vs B: Enter vs Button
SELECT VARIANT, SOURCE, COUNT(*) AS CNT
FROM TRACKING_EVENTS
WHERE EVENT_NAME = 'SEARCH_SUBMITTED'
GROUP BY VARIANT, SOURCE
ORDER BY VARIANT, SOURCE;

-- เปรียบเทียบ A vs B: เวลาเฉลี่ยถึงคลิกโรงแรมครั้งแรก
SELECT VARIANT,
       AVG(MS_TO_FIRST_CLICK) AS AVG_MS,
       COUNT(*) AS N
FROM TRACKING_EVENTS
WHERE EVENT_NAME = 'FIRST_HOTEL_CLICK'
GROUP BY VARIANT;
